(WIP) Test: Verify if secrets are encrypted
lfn-cnti/testsuite pull request #1971
Opened 2024-04-15 07:21 UTC by haskojur

## Description
By default in kubernetes system, encrypting of data inside object like secret is not enabled. They are only encoded, which means, that they can be easily decoded using `echo "<secret_data>" | base64 --decode` command.
Encrypting of secret is possible in newer versions of kubernetes. When this configuration is done, all newly created secrets has encrypted data.
This testcase creates new secret with random suffix (to avoid confilct), Then it will get data value of secret and use base 64 decode, to get initial value of data. In case encryption is not working, we will get same value decoded and testcase will Fail. If the value is different, it means, that data are encrytped and testcase will Pass.

## Issues:
Refs: #1970

## How has this been tested:
 - [ ] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [X] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [X] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

2024-04-15 22:08 UTC, agentpoyo commented
Please create WIP or DRAFT PRs as DRAFT's when creating, this will prevent any accidental merges as "Draft" status will grey out the "merge" button until they're actually ready for review and merging.

2024-04-19 13:58 UTC, ptacemic commented on src/tasks/utils/utils.cr
> +  `kubectl create secret generic #{secret_name} --from-literal=#{key}=#{value}`
this looks little bit strange, why we are not using "KubectlClient" in this context ?

2024-04-19 13:59 UTC, ptacemic commented on src/tasks/utils/utils.cr
> +  `kubectl delete secret #{secret_name}`
same  here

2024-04-19 13:59 UTC, ptacemic commented on src/tasks/utils/utils.cr
> +  encoded_data = `kubectl get secret #{secret_name} -o=jsonpath='{.data.test}'`.strip
same  here

2024-04-23 16:12 UTC, taylor approved these changes
lgtm

2024-05-03 07:20 UTC, haskojur commented on src/tasks/utils/utils.cr
> +  `kubectl create secret generic #{secret_name} --from-literal=#{key}=#{value}`
Fixed :)

2024-05-03 07:20 UTC, haskojur commented on src/tasks/utils/utils.cr
> +  encoded_data = `kubectl get secret #{secret_name} -o=jsonpath='{.data.test}'`.strip
Fixed :)

2024-05-03 07:20 UTC, haskojur commented on src/tasks/utils/utils.cr
> +  `kubectl delete secret #{secret_name}`
Fixed :)

2024-05-03 07:21 UTC, haskojur commented
@HashNuke I think this one is ready for test

2024-05-14 13:42 UTC, martin-mat requested changes
spec test(s) missing

2025-03-13 10:15 UTC, closed without merging

2025-03-13 10:15 UTC, martin-mat commented
replaced by #2238